from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Mapping

from crisp.v3.migration_scope import all_required_components_frozen, resolve_pr03_metric

REQUIRED_CI_CANDIDACY_REPORT_ARTIFACT = "required_ci_candidacy_report.json"


@dataclass(frozen=True, slots=True)
class GateEvaluation:
    gate_id: str
    passed: bool
    detail: str


@dataclass(frozen=True, slots=True)
class RequiredCandidacyReport:
    schema_version: str
    comparator_scope: str
    channel_name: str
    promotion_candidate: bool
    required_matrix_mutation_allowed: bool
    human_explicit_decision_required: bool
    pr_gates: dict[str, dict[str, Any]]
    vn_gates: dict[str, dict[str, Any]]
    np_exclusions: dict[str, bool]
    operator_surface: dict[str, Any] = field(default_factory=dict)


def _strict_consecutive_green(window: list[bool], *, required_length: int = 30) -> bool:
    return len(window) >= required_length and all(window[-required_length:])


def evaluate_pr_gates(
    *,
    comparator_scope: str,
    channel_name: str,
    channel_contract_complete: bool,
    sidecar_invariant_window: list[bool],
    baseline_value: float | None,
    metrics_drift_window: list[int],
    windows_ci_window: list[bool],
    rc2_frozen_regression_green: bool,
) -> dict[str, dict[str, Any]]:
    pr03_metric = resolve_pr03_metric(comparator_scope)
    gates = {
        "PR-01": GateEvaluation("PR-01", channel_contract_complete, "channel formal contract ADR complete"),
        "PR-02": GateEvaluation("PR-02", _strict_consecutive_green(sidecar_invariant_window), "30 consecutive sidecar invariant runs green"),
        "PR-03": GateEvaluation(
            "PR-03",
            baseline_value is not None and baseline_value >= 0.95,
            f"{pr03_metric} baseline met",
        ),
        "PR-04": GateEvaluation(
            "PR-04",
            len(metrics_drift_window) >= 30 and all(value == 0 for value in metrics_drift_window[-30:]),
            "metrics_drift = 0 across last 30 runs",
        ),
        "PR-05": GateEvaluation("PR-05", _strict_consecutive_green(windows_ci_window), "Windows CI 30 consecutive runs green"),
        "PR-06": GateEvaluation("PR-06", rc2_frozen_regression_green, "no rc2-frozen regression on PR branch"),
    }
    return {gate_id: asdict(gate) for gate_id, gate in gates.items()}


def evaluate_vn_gates(
    *,
    full_scv_mapping_frozen: bool,
    all_mapped_components_generated: bool,
    all_projectors_integrated: bool,
    formal_contracts_complete: bool,
    sidecar_invariant_30_green: bool,
    verdict_record_migration_complete: bool,
) -> dict[str, dict[str, Any]]:
    gates = {
        "VN-01": GateEvaluation("VN-01", full_scv_mapping_frozen, "full-SCV mapping frozen"),
        "VN-02": GateEvaluation("VN-02", all_mapped_components_generated, "all mapped SCV components generated by v3 channels"),
        "VN-03": GateEvaluation("VN-03", all_projectors_integrated, "all projectors integrated to SCV core"),
        "VN-04": GateEvaluation("VN-04", formal_contracts_complete, "all corresponding channel formal contracts complete"),
        "VN-05": GateEvaluation("VN-05", sidecar_invariant_30_green, "sidecar invariant test 30-run green"),
        "VN-06": GateEvaluation("VN-06", verdict_record_migration_complete, "verdict_record.json authority migration complete"),
    }
    return {gate_id: asdict(gate) for gate_id, gate in gates.items()}


def evaluate_np_exclusions(
    *,
    channel_name: str,
    has_rc2_component_mapping: bool,
    channel_contract_complete: bool,
    baseline_met: bool,
    windows_stable: bool,
    sidecar_only: bool = False,
) -> dict[str, bool]:
    return {
        "NP-01": sidecar_only,
        "NP-02": not channel_contract_complete,
        "NP-03": not baseline_met,
        "NP-04": not windows_stable,
        "NO_RC2_COMPONENT_MAPPING": not has_rc2_component_mapping,
        "NOT_FULLY_COMPARABLE": not all_required_components_frozen(),
        "CAP_ALWAYS_EXCLUDED": channel_name == "cap",
    }


def emit_required_ci_candidacy_report(
    *,
    comparator_scope: str,
    channel_name: str,
    pr_gates: Mapping[str, Mapping[str, Any]],
    vn_gates: Mapping[str, Mapping[str, Any]],
    np_exclusions: Mapping[str, bool],
) -> dict[str, Any]:
    pr_pass = all(bool(gate.get("passed")) for gate in pr_gates.values())
    excluded = any(bool(value) for value in np_exclusions.values())
    payload = asdict(
        RequiredCandidacyReport(
            schema_version="crisp.v3.required_ci_candidacy/v1",
            comparator_scope=comparator_scope,
            channel_name=channel_name,
            promotion_candidate=pr_pass and not excluded,
            required_matrix_mutation_allowed=False,
            human_explicit_decision_required=True,
            pr_gates={str(key): dict(value) for key, value in pr_gates.items()},
            vn_gates={str(key): dict(value) for key, value in vn_gates.items()},
            np_exclusions={str(key): bool(value) for key, value in np_exclusions.items()},
            operator_surface={
                "semantic_source": "v3",
                "label": "[exploratory] required-CI candidacy",
                "verdict_primary_mutation_forbidden": True,
            },
        )
    )
    return payload
